import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DocsExample } from '../shared/app-docs-example';
import { HELLO_SPEC } from '../examples';

@Component({
  selector: 'app-overview',
  imports: [DocsExample, RouterLink],
  template: `
    <section class="max-w-2xl">
      <h1 class="text-3xl font-semibold tracking-tight">ng-json-render</h1>
      <p class="mt-3 text-lg text-zinc-600 dark:text-zinc-300">
        Angular renderer for
        <a
          href="https://json-render.dev"
          target="_blank"
          rel="noreferrer"
          class="text-indigo-600 hover:underline dark:text-indigo-400"
          >json-render</a
        >. It renders a JSON spec, generated by an AI model or built by your
        server, using your own Angular components.
      </p>
    </section>

    <section class="mt-8 max-w-2xl space-y-3 text-sm leading-relaxed text-zinc-600 dark:text-zinc-300">
      <h2 class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Overview</h2>
      <p>
        json-render is a framework for <strong>generative UI</strong>: an AI
        model generates the interface (which components to show, how to arrange
        them, what data to bind and which actions to wire up), but only from
        components and actions you define. The model outputs JSON, not code.
        Your app validates that JSON and renders it with its own components.
        Nothing in the spec is executed.
      </p>
      <p>
        The same approach works for <strong>server-driven UI</strong>, where
        your backend builds the spec instead of a model.
      </p>
      <p>
        The catalog, spec format, prompt generation and streaming come from
        <code>&#64;json-render/core</code>, so the upstream
        <a
          href="https://json-render.dev/docs"
          target="_blank"
          rel="noreferrer"
          class="text-indigo-600 hover:underline dark:text-indigo-400"
          >json-render docs</a
        >
        apply. ng-json-render adds the Angular rendering layer.
      </p>
    </section>

    <h2 class="mt-10 mb-3 text-lg font-semibold">How it works</h2>
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      @for (c of concepts; track c.term) {
        <div
          class="rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"
        >
          <div class="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
            {{ c.term }}
          </div>
          <p class="mt-1 text-xs text-zinc-500 dark:text-zinc-400">{{ c.desc }}</p>
          <code class="mt-2 block text-xs text-indigo-600 dark:text-indigo-400">{{ c.api }}</code>
        </div>
      }
    </div>
    <ol class="mt-4 max-w-2xl list-decimal space-y-1 pl-5 text-sm text-zinc-600 dark:text-zinc-300">
      @for (step of flow; track step) {
        <li>{{ step }}</li>
      }
    </ol>

    <h2 class="mt-10 mb-3 text-lg font-semibold">Example</h2>
    <p class="mb-4 text-sm text-zinc-500 dark:text-zinc-400">
      The spec is on the right and the rendered output on the left. The input
      is bound to <code>/name</code> with <code>$bindState</code>, and the
      greeting reads it with <code>$template</code>. Edit the name to see both
      update.
    </p>
    <app-docs-example [spec]="helloSpec" />

    <div class="mt-10 flex flex-wrap gap-3">
      <a
        routerLink="/start"
        class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500"
        >Get started</a
      >
      <a
        routerLink="/ai"
        class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-medium hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-800"
        >Generate UI with AI</a
      >
      <a
        routerLink="/components"
        class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-medium hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-800"
        >Components</a
      >
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OverviewPage {
  protected readonly helloSpec = HELLO_SPEC;
  protected readonly concepts = [
    {
      term: 'Catalog',
      desc: 'The components and actions the model may use, with Zod-typed props and descriptions.',
      api: 'defineCatalog()',
    },
    {
      term: 'Spec',
      desc: 'The JSON the model generates: a flat map of elements with type, props and children.',
      api: 'Spec',
    },
    {
      term: 'Registry',
      desc: 'Maps each catalog type to the Angular component that renders it.',
      api: 'defineRegistry()',
    },
    {
      term: 'Renderer',
      desc: 'Renders a spec using a registry.',
      api: '<jr-renderer>',
    },
  ];
  protected readonly flow = [
    'You define a catalog. catalog.prompt() turns it into a system prompt.',
    'The model responds with a spec, streamed as JSON patches.',
    '<jr-renderer> renders each element with the component registered for its type. Types not in the registry are skipped.',
    'Components raise actions. The spec only names them; your handlers decide what runs.',
  ];
}
